### PR TITLE
rebuild for python3.12 + libpq16

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Applies python 3.12 + libpq16 migrations to 2.x.x branch. 

Anybody have thoughts on if 2.x.x should be added to abi migration so that it continues to receive migrations?  psycopg 2 and psycopg 3 are not compatible and can live side-by-side, so folks like me will be running both into the foreseeable future as I work through migrating various code bases....

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by xylar** [comment]
Thanks @akrherz!

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
CI seems to be getting hit pretty hard these days.  I'll put the automerge label on and we'll see how it goes...

**Comment by akrherz** [comment]
Thanks @xylar , sorry about embedding my question above in the PR, but you have thoughts about adding an abi migration branch to main for this?   I'd be happy to PR it, of course.

**Comment by xylar** [comment]
@akrherz, I see, I did miss that.  Feel free to make a PR to `main` to add 2.x.x to migrations.

**Pull request merged**
