### PR TITLE
Make sure not to install dependencies from PyPI

### LINKED ISSUE #78: psycopg 3.1.9 pip installing typing-extensions and tzdata overwriting conda dependencies
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I create a new environment containing just psycopg 3.1.9, I see all the listed dependencies are from conda-forge.

After the environment is created though, when I list the installed packages I see the typing-extensions has been overwritten by a lower version of the pypi package, and tzdata has also been replaced by a pypi package. See screenshots below:

image
image

### Installed packages

```shell
N/A
```

### Environment info

```shell
active environment : test
    active env location : C:\Users\OwenLamont\miniconda3\envs\test
            shell level : 4
       user config file : C:\Users\OwenLamont\.condarc
 populated config files : C:\Users\OwenLamont\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.11.3.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\OwenLamont\miniconda3  (writable)
      conda av data dir : C:\Users\OwenLamont\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\OwenLamont\miniconda3\pkgs
                          C:\Users\OwenLamont\.conda\pkgs
                          C:\Users\OwenLamont\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\OwenLamont\miniconda3\envs
                          C:\Users\OwenLamont\.conda\envs
                          C:\Users\OwenLamont\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.11.3 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by xylar**
closes #78

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@owenlamont, I'm 90% sure this will fix #78.  I will probably need to mark the previous build of 3.1.9 as broken.  I also haven't investigated how long this has been an issue (I hardly dare to find out because it would be a lot of work to fix in previous builds).

**Comment by xylar** [comment]
It does, indeed, seem to be a problem in 3.1.8 and probably earlier.  I'm hesitant to mark the package as broken because that might actually make things worse for folks than having the packages get clobbered.  Until folks report ongoing problems, I'm going to hope fixing this for 3.1.9 and subsequent releases will be sufficient.

**Comment by owenlamont** [comment]
Thanks for resolving this, I'll test again later too. No problem about the old versions, I know how difficult it is to update them.

**Pull request merged**
