### PR TITLE
Update to v3.0.8

### LINKED ISSUE #53: psycopg3 was released, is there a plan to put it on a feedstock?
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I don't know where the correct place to ask is. Psycopg3 [was released](https://www.psycopg.org/articles/2021/10/13/psycopg-30-released/) in October 2021. Is the plan to update this feedstock to 3 or to open a new one in parallel with this one?

### PR DESCRIPTION
**Pull request by xylar**
This requires a complete overhaul to the package names, how they are built and where they come from.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #53

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
So having played around with this off and on for nearly 2 weeks, it seems like `psycopg-c` will be hard to build because it requires `cython >=3.0.0a5`.  This alpha version hasn't been built on conda-forge and that's well beyond my expertise.

There's also a python wrapper for `libpq` that ships with `psycopg` but that doesn't seem to be working with conda-forge's `libpq` under OSX:
```
couldn't import psycopg 'python' implementation: dlsym(0x7fddd6e33cb0, PQsslInUse): symbol not found
```
It's not clear to me if this is a problem with the OSX build of `libpq` or something else.  Again, pretty far beyond my expertise.

So I'm pretty stuck for the time being.  I'll revisit this down the road but suggestions are welcome.

**Comment by mattip** [comment]
Pinging @dvarrazzo for thoughts about how to work around the cython requirement

**Comment by dvarrazzo** [comment]
Hi @mattip 

I don't know the context, I might be uninformed here. However, Cython is not a requirement to install `psycopg-c`: It is a dev-time requirement in order to create .c files from the .pyx files. The `psycopg-c` distribution package only includes the generated .c files and doesn't include the source .pyx files, so it's actually impossible to use Cython to build the package from there.

If you are asking how to build psycopg-c without using Cython, well, no. Cython is the *language* that the `psycopg_c` extension module is written in, not an optional component.

If you have built psycopg2 so far, as the title of your package implies, you should be able to build the `psycopg_c` module from the content of the `psycopg-c` distribution module, there is no Cython dependency to do so. If you want to build it from the git repository code you will need Cython.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by dvarrazzo** [comment]
Nice, I'm pleased :)

Please also notice what is in the psycopg_c  setup.py: it is [specifically designed](https://github.com/psycopg/psycopg/blob/edb7c7a0/psycopg_c/setup.py#L50-L53) so that if it finds .pyx files it will assume it's being run from the git source, so it has to build the c files from Cython source; otherwise it assumes that it's being run from a sdist package. Cython is imported only in the first case.

**Comment by xylar** [comment]
@dvarrazzo, oh, that's great!

It may take me a bit to get this up and working.  I'll be back in touch if I run into trouble that isn't conda-forge specific.  Thanks again for your response.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I had trouble with python 3.7 and 3.8 incorrectly trying to use `gcc` instead of ` x86_64-conda-linux-gnu-cc` with v3.0, but local testing suggests that this is not a problem with the latest version (v3.0.8).

Additionally, I realized that there is not a version of `psycopg-pool` for each version of `psycopg`, so it seems like that package would need its own feedstock.  I'm going to let that be for now.

**Comment by xylar** [comment]
Nope, apparently not fixed.  Must be a conda-forge issue.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf and @mattip, do either of you have the time (or expertise) to give this a look?  In particular, it would be good to have someone else sanity check the way I determined `LDSHARED` for python <= 3.8.  I'm surprised this isn't an issue for other feedstocks.  Without the fix, I get:
```
  /home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_build_env/bin/x86_64-conda-linux-gnu-cc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/work=/usr/local/src/conda/psycopg-c-3.0.8 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -fPIC -I/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -I/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/python3.7m -c psycopg_c/types/numutils.c -o build/temp.linux-x86_64-3.7/psycopg_c/types/numutils.o
  gcc -pthread -shared -B /home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/compiler_compat -L/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath=/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,-rpath-link,/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/work=/usr/local/src/conda/psycopg-c-3.0.8 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include build/temp.linux-x86_64-3.7/psycopg_c/_psycopg.o build/temp.linux-x86_64-3.7/psycopg_c/types/numutils.o -L/home/conda/feedstock_root/build_artifacts/psycopg-split_1642727957891/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -lpq -o build/lib.linux-x86_64-3.7/psycopg_c/_psycopg.cpython-37m-x86_64-linux-gnu.so
  error: command 'gcc' failed: No such file or directory: 'gcc'
  Building wheel for psycopg-c (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for psycopg-c
Failed to build psycopg-c
ERROR: Could not build wheels for psycopg-c, which is required to install pyproject.toml-based projects
```

**Comment by mattip** [comment]
Sorry, I am more of an end user than a developer at conda-forge, although I do maintain a few recipes.

**Comment by xylar** [comment]
@mattip, no worries.  I thought that might be the case but I had noticed that you were a maintainer on a feedstock I stumbled across recently so I figured it didn't hurt to ask.  I'm pretty confident in this work but it doesn't hurt to have another pair of eyes on it.  @ocefpaf can presumably review it when he has a spare moment.

**Comment by ocefpaf** [comment]
> I'm pretty confident in this work

Let's give it a try and we can always mark as broken if it doesn't ;-p

**Comment by xylar** [comment]
Great, thanks @ocefpaf!

**Pull request merged**
